package root;

import weekOne.stepFiveCSFreqArr.ComputingFrequencies;
import weekOne.stepFour.ClumpFinding;
import weekOne.stepSixCSConvPatt.NumberToPattern;
import weekOne.stepSixCSConvPatt.PatternToNumber;
import weekOne.stepThree.PatternMatching;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static weekOne.stepThree.PatternRC.getReverseStrand;
import static weekOne.stepTwo.PatternCount.getPatternCount;
import static weekOne.stepTwo.FrequentWords.getFrequentWords;

public class Main {

    public static void main(String[] args) throws IOException, URISyntaxException {
        /**
         * Calling getPatternCount method from PatternCount
         * class to test the method on the provided dataset
         */

        System.out.println(getPatternCount("ATACGCGATAGTTTCCATA","ATA"));

        /**
         * Calling getFrequentWords method from FrequentWords
         * class to test the method on the provided dataset
         */

        System.out.println(getFrequentWords("ATACGCGATAGTTTCCATA", 3));

        /**
         * Calling PatternToNumber method
         */

        /**
         * Calling getReverseStrand method
         */

        System.out.println(getReverseStrand("AGTCGATTTGGAGCTTCGTAGTTATCCTCGAGGGGGTGT" +
                "ACTGTCGTGACGCGAAAGGTAGCAATCTAATCCCGCTCAGGGCGAGAAGAACACTTGAATCGCTAAA" +
                "TCCTGGGCTCCGTAAGGCTAGCAATGCCAGACCAACGTTGTGCTTATTGAATTCATGCCCTAAGCAT" +
                "GCCAACATGTGGTGCGGCCCCCTTTTTCTCAGGGATTAGGCCTGAAATGTTTGGTTGTTGGTTCTCG" +
                "CCGCTCAAATATAAGGTGTAAGATCGACACGAACAAACACTGTAATGGTCTTTTCCAAGGTTATATT" +
                "CCAATGAGGGTTTGGCGGCGACGGGTAACGGCAAGTTGCTCGATCAGTTGGGATGCCGAATACTACC" +
                "TATAGAGCCTAAATATGCAATCGTGAGGGTATTGGGAAATACGTAAGATCATTCCGATACTGTGTTT" +
                "CATATCTCGGGGGCACCGAATATCGTGCTTACACCATGGGAATTAAATCCTGGCGATCATGAACCCG" +
                "TCGTATCCCCCAGAGGGCGCGCCACTGAGGCAGAAAGCCATCGGGGGGAATTTTGCCAGACGGACGA" +
                "GCTCTAGGTCTTGGCCCCTCGTTACGACAAAACGAAATGGATGATTAACAACCAATGACAGACCGCC" +
                "GCTTATTCAATGAACATCATCAGGGAATAAGGCAAGCCCAAAAAGCAGGCCTCTATATCCACATAGC" +
                "GTCAGATGCACCAACGTTCGTTCGGGGAGCGACCAGGAAAGTCGTTAGCGCAGCGAAACTAACCATT" +
                "TCTACCTTTACTAAGCGCAGTCGTGGCGGTCGCTAAACCTTACCGACAACCGCCCCTGAGCCACCGG" +
                "GATATCTAGGGCGGGTCCCTCTCGTGTGAGGGTTGTTGTGCTTGTTTCCCGTTTAGCATTACGCTAT" +
                "AGAGTCGGAAGAATGACGATCACTCCTATTACTCTACCCCCCCCGCCCGACGTTTACAGACGATGTT" +
                "AAATCTTAACAAGTGTCAGGCTATTGGCACTAGATTCCTATCGGCGCGATTGGATCCCAGCGTACCA" +
                "CTGATGGCCACCTCACTTGTCCTCGCGTCGAAGTAGGCTTTTACTACGGCCTCCCGGCGCGTTGAGC" +
                "TGGCGACTATCCGCAGTGTAAGTCTAAGCGTCCATTACTCGGTTTACTAAGATAGGGGGTACGAGCA" +
                "ATCAGACCCTCCCAAGTGCAAGCGACCCGATGGGTCGATGTAAACCGTAAAGGCCAAGCCATGTACA" +
                "CCATCGACAACAGCGTAAGTCCTATCCTATAAGAGCAGTAGATCTAGGTTAGTTGGACAACTCTGCA" +
                "GTGAGGAGCCTTGAAAAAATGTCCATACATGCGGACGCCTGCCTCTATGTGGACCTGATAACATCTC" +
                "CTGTTTAGGCACGAGGGCAAAAGTTAAAACTTCTTTCATGTTATCACGGGCACCTAACGCAACCTCT" +
                "AACTCACTACTGTGAGGCTTTAGACATGTTGGGCCCCTTTCCTTCGATCACGCGACCGTCACATAGC" +
                "ATGGGGGTTCGTTGTTGACCATCATAGCTCCACCAAGATCCGTGGAAATGTAGGTGGCCATTCCGTT" +
                "GGGGTTTAACACAGTCAACTAGAAAGGTCCAGGGGTGCCCAGTAGCGACTCATAGGTCTCGACGGTA" +
                "ACGAACCGGTCGATACAGTCATTTCTTGTGGAACAGAAAGCTCCCCCTGGCCCGCTCTAACACCACG" +
                "CTGACGATAAGGACCAATAAACCCCTCTATAATTCAAATAATCCTGGGAATAGCACTACTGATTGGA" +
                "CCCATTCAACATCGTATCCCGCGACGCTTCCGCCAGCTATTTCTGCGGATCCGAGGTCAGGTTCTGT" +
                "TCGCGCTTCAGAATCCAAGCAGACCTACGAGGTTCAAACGGGGCAAATATCAACCTCGCGAGAAACA" +
                "GTTCAGGTCTAGCTATGGATAGCCCACTCACAGTTTCCTTAGTACGCAAGTTGTTTCGCCATATCTA" +
                "CGACGATGGGACTCTTAGAGAGGTCCCCCCACTGGGCGCTGACGCAGCTATCAGCCCTGATTAAACC" +
                "TAGACTGTGCGATGTTGCCGTATAGCCCAAATCGTTATCACAGTTGGTATATGTCTTACCGAGCGGG" +
                "ATACCGTAGCTCGCTGACGTATCGCGCGAAGCCGGAACGCTAAAGTTCGGCTGTAGACATCTGTCCT" +
                "ATTTGCTTAGGGCTAAGTCTCACAAACCAATGATCTACCTCGCAGTGGGCTACGATCCACATCCTGT" +
                "AGTTACCCCGGAATAAGTATGTCACCTGGACTCTGACGTCACCTCCGCTGCGACATGATAGCGGTCG" +
                "TGCCGCGGGGACTGCAGAACGCCCCCTGTTATAGAATCTGGGTATCCTGGATTTTCCTTTAAAAAGG" +
                "GTCAATTCCTTGGCCCTCGTGTCAAAAATTAGATAACTGGAGTTCCGGATCTACAGACTCGAGGCGG" +
                "CATACCTGATAACCTCAAGTGTCGCACGGTGCGCATGCGGCGATCGCCCGCTCGGGTAGTGCCTTAC" +
                "TCAATGGCGACTCGTTGCAGGTAGTATAACGCAAATACCCGCCTGCCCTTTGGCCACGCAAGGGCGG" +
                "GCAGTTTGGGTTGTGATATTGGAAGAATTTATTTAGCGCCGGCATCGACTGGTAATTGAACAGGCAT" +
                "CAAGCACGGGTCAACTATAGCGCAACATTATGCTTTGTAGACAGTTTGTCTCTCCGACACGGTCTAA" +
                "TAGTCCATCTGTGATAAGAATCGCGTCATGTACCCTAGAGCCCCTCCCAACGCTTTCCTTTTTGGGT" +
                "GTTAGATTCTAGTTCCTACTCAGCGGTAACCAGGGTCTCTCTATAGTAGACGAACGGTCGCAGATAT" +
                "ATCAGTGAGGCTTGGTCAAAACCGGTGGCCCGCGACTCAAGGTTTGGTCCCTTATTTGGCGTTTTTA" +
                "CCTTACTCAAAGCGCCAGTTGCCTCGGATGACGGCCGCGTCCATTTCCGCATATCATGTCAAGTACT" +
                "GAATCGAGAGGTAGAGTTCACCCCTTCCCTCCTCACAGCGTGAGGCGCCGGATTGCGAGTCCTCCTG" +
                "CTTGACACTGGCCGCCCAAGTTATGCCGAACGTACCGGCTCGCCCCATGGAACACCATCACTCTTGT" +
                "CGCATTATCTTCCGCTACCAAGGTGAAGTCAGAAAAAGAGCGACCGCCCAACACTCTGAGCTCCCAC" +
                "CGTTGGGTCGGCTCGCCGGGGTTAGCTAAGCTGTTACGATATGCTTAGGCAGATCACGATTTTCTGA" +
                "GACGTGAACGACCATGCACACGGAGCAGCAAGAAGTCTTGGCTAGAAAGCATCCTATACGCGGGTCC" +
                "CGCGTGCTCGCTCGGGAAACAGGAACTATATGGGTGACTTCAAATTCTGGGTAATGGGAGATATTTC" +
                "AGACGCAGAGGCGATGCTGCTGCCAGGCGATGCGAAGACTTGCCATCCTTGACCACCCGACCATTAG" +
                "GACAATATAGAGAAAGTGTCGGCTCCAACTACAGCCGCCACTCCAACTAAGCTATCTTCAGGACATG" +
                "GATGGGCGGTAGGTGTCCCCAGACCAGCCAGGATGTACACATAAGAAAGTATTATTACCCGCTGTTA" +
                "AATCATCTTACATTGGCCTTGTCCACCATACACGTCGCGGGGAGCGTTATCTCTAGCTCGTTAATGT" +
                "GCCCAACAGCCCCTCTATGTAGGTCGAGAGACGGCCATAAGTCGAAACTCGACACAATATCGGTATT" +
                "GTAGACGACGTCCACACGAGCAGTTGTCTGAGTTAGTTTTAAATCCGTATACCCTTACGGAATGGAA" +
                "TGACTTAACGGTTGGTACCACCTTGGACTTAACCGTAAGTTTGTCAGAGCTGTAGGTACTCGCTCGT" +
                "AACAGTTGCACGCATGTTGAGCCGGAGGGAATTTATTATTGCCCCCCGATAGCCTGGATATTGAAAA" +
                "AGCCCATCGAGACCGTTCGAATACAACAACGGAAATATGACCTAACAATGAGTCTAGCTAAAGTATT" +
                "GCCGTCAAAAGGTCGGTACAATAAGGATGGGTTTGGTCAGAGGCGCTATGGGCCAAACATCGCATTT" +
                "AGTGCCATAGTCTGCTCAATAGGTCAATGGAGTATTACAGCAGGCGAATTCATTAGCGGCCTCGTGG" +
                "GCTTACGGCTTTATAGCCACACACCCTCAGCGGTGATGTACGCGGCATACTTACCATGTGGCGTGCC" +
                "AGACTGACAGTGATATTACTAAACTCGCTCCGGAAATCGGAAGCTGGATATTCCAGAAGCGAGATTG" +
                "CCTTGGAAGGAGGCGGAGCGTGACTGTGAGACCGGTGAAGCACACTAATCATGCAAGTACATGCAGA" +
                "GGGCAACTCATACCAGGAGACTTGACACTCGCGCGACACTCACCCGGTTTTCGATGACATACGATTT" +
                "GGCAAGTCGTTAGCTGAGTCCGTCAAGATGGTTTCAGTCTATTTTTAGGGTTTTATAGCTTCACGGA" +
                "GGATGTCATAAGTACTCTGAACGTGGTTTACGCCGTGAGGAGGCTCATCAGCTGCCCTACGAGCAAT" +
                "TGAGCTAGTCTCCTTTCGTGTGAACTGACTGCTATCGTTCATGACGACTGCACCTCCTGCTAAGAGA" +
                "TCACATAGCTCACAGGACGGGAATTAAATCATAGCTCTAGGGAACAGCTCTTCGGACGCTTATTAGC" +
                "CTGAGGGACGGGTTTCCCTGGAAAGCTGTAGAGTGTGACATTGTTTTGGGGCTTTTTCATGTTCCTC" +
                "AACCGATCGTTACTGACCTGAATGAATTAACATCCAACGGACCGTGAAGAGTCTCTCATGGCTCGAT" +
                "TGAGTACAGTTTGGTTTGTACAACACGGATAGGATTGTAGGGTGCATCTTCCCCCTCATGTAATGCC" +
                "AGGCGCCACACACAGCAGGTAGCCGTTAGCTAGTATCCGGTGGGACTAGTTGACGCATGTGATCGCG" +
                "CGCTTACCGCAAGTAGCCACCATACCTTAGTGAATGAAGAAAGGCAACAGCTCATCGGTTTGAGAGT" +
                "ACCCAGGTTTGGTTGCGGTGTCTAACTACCGGACGAAACCGTAACATGGTATGATGTCGAAGCCATC" +
                "CCTCGGTATGGTAGCGCGCGAGTCACTTTATCGTTGCAACTCACTGATCATCTAGCCTATTGGGTGT" +
                "GCGTTGTCGACGCTCTTTGGGCGTTGAGTTGTCGGCATGGAAGATTTTAATGTACAGTTGAGCTTGG" +
                "AAGGTGTCACCGTCAACATAAACTTAGCAACATAGAAACCTATGAACATGTTTCGTCCTCGTGATCC" +
                "AATGGCGACTTTAGAGGGAACGAATATTACGGATGCAAACTGGGTTCGCATGATAAGTGAGCTATCC" +
                "TTAGATATTCGCGAGCGACAAATGCTTGAGTTACAACCTTGACACGCCGAGCAGTATCCTACGACCG" +
                "AGTTTTAGTCAGATCTAGGTATGATCACGACATCCGACCATTATCATAAAGACAACTGAACTGACAA" +
                "AGAGCGGGCATGGGTCATGTACGCCGCCATTTATTGTTGAACTAGTAATGAGGCGAACCCTTAGGAT" +
                "GTCAGGGAAGAGCAAAACTTTTGTCCGCCGGTCCGTACGTTAGTCGGAGCCTTTGTCAGTATTTAGT" +
                "CCATTGACGATATTAGACGTGGGCTCTACAGGCAATCACCACGTGCTGTTTCCATCCTGCCTTGCAT" +
                "GGGGTAACCCAAAGTCTACAGCCTCGGTGAGGTCCCAGGTGCATAAAAAGATCGCCCGGTAGGTTAT" +
                "ACGGTCACCTAGGTAGGTCAAACGGCTGGGCCAATACGCCTCGACCTCCGACGTATGCCTTTCGGTT" +
                "CCACTAGCGTGCGTGGGAAGCATGGATCGGAGGAAGCTGTTCGTTCCTGGTTCGCTCGTCAGGACTA" +
                "CGCTCTTATTATACTGCCGATGTCAAAACAGGCGTGGTACGGTGCTCTGAAATGTTTTGTGACTTGC" +
                "GGTCTCCGTCTTAGTAGCTGATAGTGAATTGGCGTCGGGCTCGTGAGCAAGGAAATAAGGGCAAAGT" +
                "CTACAGGAGCCCGACCGTTTCTCATTTTTGATCACATGAGCGGCGGGTAACAAGGTCACGTAAAAAT" +
                "CCTTCGTTCGTCGTGCCGTTCTCCGCGACTATGGTGGAGGCATTTTGCAGCACTAAAACCAACAACC" +
                "ACATTTTAAAGCGTAGGTAGGCCCTCTCCTGATCTTGTACGTCCAGCCGCACACGCGACTTCCCCAT" +
                "GCCTGGCGGGTCCATGCGCCAACCTTTTGCCACTGACTCTCAAAATGAAATAAGACACGTAATACGG" +
                "TCAGGCCCCTTATACATAATCCCCTAATGTGAATCTTCCCGTGGAACTAAGCCTCGGACTTGATCCT" +
                "TGTGTTTGATTTAGCACCCCCGACACTCAGAACTTCGAACGAGAGGGGTGCCCGGCTACTTCAATAG" +
                "CTACCGAGAGGTTTGCAAGCGCTTTTTTAGCCTCACTATCCCTTCACACGCTTCCGATCGGCTGTCG" +
                "GTAAATGCCCCCTCCGGCTACGCATATATGCAGGTATCTGACAACCAGGCAGGCTAGATGGTGCACC" +
                "GCTCGGTTATCATGAGCCAGGGTTATTCCAACCCCAAAAAGACATCGCATCAACTAATCCGCTAGAA" +
                "TTTCTCAAAGTCCGGCGCAGTCCAATGACGCTCTGAGGTCTACCGTTTAAACTTGATTGATTTTCCA" +
                "AATAAGGCCAGACACCTAATGCAGCTACGAGGAACCTTCCCTTGCTGAGCCGGCAGCTGAAACACAA" +
                "AAAGGGAGACGAACCAAAGAGGGGATGCAGGGCGTAGCGTGCACACGCAATGTGGGGGTACCTGATG" +
                "ATACGTCGGCCAGGCGATGTGAAATTAAATAACCTCTCACCCCCACTCGTCGGATGGTCTAGTTAAC" +
                "GATTTCCGTCAGCACCAAGAGATTAATTGTCAATGAACAAGGTATGCATGGGCTCCCAGAGCGGTTG" +
                "TGGAAGTCTTAGATTAAGGTGAGACGGCAGATGTCCAATCATGGTCTCGTCCGCCATCTAGATTATT" +
                "ATACTCCTAGTTATCCTGGGGCATTATGTGTCACCAGCCTAGCTCACAAATGTCTGCCAAGAAGGCC" +
                "TCTGGAGGCCAATTCATGATTGGTAAAGGCCAAGGTTTATCTGAAATGTCGTCGGCACATCATAGTC" +
                "GATATATCCGATGAGAGCTTTCCAAACACATTTAATCAGCACTACCGGGTGTTGTATGTTATTGAGG" +
                "GGGCAGAGGACGTTGCTCTCTCATTCGGTCTGCCGGTGCCTTTTATGATCACCCCAACCGTTCATTC" +
                "AGTGGCCTCGCCACGCGCCACCGAGCCATGACGCTGAGGGTGATACCCGTGGCCCGCGCCTCGAGTA" +
                "GCTGTATATTGTCTAGGACAAGTCAATGGCACATGTAATATACGGTTAGGATCTATACACTGGGTTG" +
                "AAACTTGAGATTATATATTAGTGTCGACGCGTTTGGTACACGGTGGGAAATCTCTCCTGGCAGGGTG" +
                "TCTTTACGCACTTGGACATAAGCACTACTTTACCTAGGGTAGTCCCCCTACAAGCGAAAATGGAGAA" +
                "TCTACTGGTTGTCCGACCAGTTATAATTGCTTTACCTAAATATCGAGTGGCAACGCGCCTGATTTAA" +
                "GTCCAACAGGAGTGACGAAGGTTTCTGCTAGCGCGGGACATTTTCGTGGCCTGGATCGTCGATGCAG" +
                "CGACTTGATGTTCAAGGGAACATCTCGACTTAGAAAAATAGGACTTTTAGCGGCGATAGAACCGTTA" +
                "CATTGATATTAGCGCGGAGAATCTGCTGCAAACCTGATTGTACTACTCCCAAGATATATTCGGAGTA" +
                "GCAGGCTGCCTGCGGGAGTCGCGATAGTCCTCTTCTACGGGCAAAAGACAATCGGCCATGATTAGAA" +
                "AATCAACTTAATATGTGTAGCTCCCGGAAGAAAGGCGCTCCTCGCCATTAACGGTGTAGTTTCGTCG" +
                "GTTGCAAGTCTAGAGAGGTCGTTGTCAATAGTATGTCTCGCAGGATAAAGGCGGGCATGGGTGTACG" +
                "CTAGCAGTAAGCTAGAATCTTCCCGGAGCGTGGACCCGCCAGGGCCCAGTCTCACGATGCTGACGAC" +
                "GTAAAGTTCTCTTTACAGACCGTCACGAATGTGCTTAGATCTCCCATCACCTCAATAACAAAAAAGG" +
                "GCCCATAGACCTAAATTAATCTGAGTATAAGCTTATTGGAAGGTCTTATGGGTGCATATATATCAGT" +
                "CTCGGGGCACAGGGTAGCCCTCACCACGGGTGCGACCGGGAGTACGGAAACTGGCGGCATTACACTT" +
                "GTTCGCCTTCCGCAGTTTGTCCGATCGCTGTGCTGAGCTGGATGATCTTAATCGATGCTCAATGACT" +
                "CGGAGAGATCCAGTCCAACACGTGCTACCGGCTAATACCAGGGTTGGATGGTTAACCACCTACTGGA" +
                "TGGTGGTTTGGGAACTCAGTTCGTTCCACGACCGAAGCTGATGTCTGACGGGCAATCCTCGCTAATT" +
                "GGATCCAGTTGCTTACACAGCCCACTGCCAATCCTTTGAGATATTTTAGGTTGTGCTGAATCGGATG" +
                "AGTATTCCGCAATTTTCTTTGATCTCTGTGCATTTGATGGGGCGTCAACTCCCTAAGCCCCAACCAT" +
                "CTCCAGTAAGAAACGCTATCTC"));
        /**
         * Calling getPatternMatching method
         */
        System.out.println(PatternMatching.getPatternMatching("ATA", "ATATTTGGGCCCTTTGGGCCATATCGGCTAATATGCTATA"));

        /**
         * Calling patternToNumber method
         */

        System.out.println(PatternToNumber.patternToNumber("CGTACGCACGAGTTC"));

        /**
         * Calling numberToPattern method
         */
        System.out.println(NumberToPattern.numberToPattern(7200,8));

        System.out.println(ComputingFrequencies.computingFrequencies("TTCTGCTCTCCTCTAAGAGACTGGGCAGTGTGTGCTTAAGGGGGATTACTCATCCCGTTCCGAGGCTAAACGAACTACCTTCGGTGGGCTCCTTGTTGGTCTTCACGAGGGGGCCGATCGGCTAACACGTGAGTATGTGGTGCGCAGCAGGGCGGTTCGGGGAGTCGATAGTACTGGAGCCGTGGTCTGTTCCGATTATTGAGTAATTCCCATTTGATCGCGCGCCTTTTCCAGCTTCGGTTTAGGGTCGTTCCGTGTAACATCAGGCTTGTAAGGACATTGGAGGGGCGAAGCGTCTGCCATCCACCCTGGGGGACGATACCTCCATACGGGATAGGGCGTTCCATGCAGTTTGAGGAAGGGACGCCCGTACAAACAATATCGGCTTGTAAGGTAGCGTACTTAAACTCATCAGTATCCCCCAGGTAGCGCAGCTAAGTGAACATTTGCGCTACTGAACTGGGAAGGGAGCCTTTATTGTGAAGCTAGTGCACACATAATCGTTTTACTCGCACTGCGAACTAAGAATCCCCCCCTTGACGGCGGCCTTAGTTAGACGCCGCTGAGGTAGCGGGAGAATGGCGAAACAGTTCCAGGCCGTCTGCCTCCTAGAAAATTCCCACTAACCAGGGAGGGGCGCTTCTTGTCTTCCGCCGTGCACACACAGGGCTTCCTATATCGCCCAAATCGCGACCGATCAAGCCAATCTATATGTTCCGTCGTGTCGAAGCCTCACAGACGGCGGGACACCCTGGGGAGGTTTGCGCGCTCG", 5));

        System.out.println("Hello");

        //System.out.println(ClumpFinding.clumpFinding("TGTCGGAGGTTTCCCACCTACGGGCCTGTGAGCTCATCCATACCACTGGAAATATAACCTTGTGGCCTATTTTCACTCGGCAGAACTATTACTAATCGTTGTATGATCATACTGGGACGGGTTCGTTGTTTAGACTAGGTCCGGTGTTTGCTGATGACCATGGCTGGAGAGCCCGCGCACTCATGCCAGCTTCCAGGGCGTACCCCTGCATTGAAGATTAAAATACCCAGGGCAACTGCACACAACCGATAGTTGGGCGCCTTAGTACGACCGGAATCTAACAGGGGTAGGTAGGTAACAGGGGTAGAGTTAGCGGCTCTGCTTCTGCGCTCTGCTTTAAGGCGCGGGAAATTACGGAACTGCATGCCTAAACCTTCCCTAAAGTAGTACCTAATGATTCCTTATATAGTGCTAACATGTCTGTGTGCAGGACAATGAAGCTAATCTATTATGATCCTACACGAGGGCCGTAGTAGTTGTTGTGTCTCGGCCGAAATATTGTGCATTTTCCCCACAGATAAGGACAGATAACAGATAAGGATAGGATTGGCCTAGAAAAGTCTGCCCATTGTTAAAACCCCTTGAGAGGCATGACGGACGGATAGAGGAACATCCATGTGCATAAATGGGTGAAGGTGCCCTACGGATTGGTGTCGTGTCGTCTCTTCGTGTCGTCGTCTCTCTCAACAACCCCGCCCGCTCAACCGCTGTGGAGCTACGGTTTCCAAGTACAAAGCTATACCACTTTGGACAAACGACCAGTAGCTGCCGATGTGACGAAGTGTCTCCACAGTACGAACGACGTACGAACGGTACGAACGCGTGTTGTGTGCGCCCATACAATTTGTGTTACTTCCTGGTCGCCATCTCTCGCTTAGGAGCAACCAAAGGGATAGTTAATCAGTATTCCGTATCTGATATGAAGTTCATGAGCCACCTCGTCTGTGGCATCTGTGCCGCCCACCCACGCTTGACGCTTGAAAGCGTGGACCTTATCTTAACGTAGACCAGTATGCCCTGATCGCTTTTAGCAGCGGTGCACTAATACTTCCCAGAGTGACGCGCTGACAGCGATTGATGCGGTCCTGAGCGAACACGGTGAAGAGATTAAGACAGTTTCAGCCACCGCGAGACCGGTGTCATGGCCGGAGTAGCGAATCCCTCTATGGATCAGCTCCACGAACACCTCAATGCGGTGCGGCACCCAATTCCCTGTTTGATACTGTTTGATTGTTTGATATTGTGTGCTATCTGAACGGGTTAGCCTAATCTAGGCGATTCGACTCGTAGTAGTAGGTGTATTAGGTGTATCGCGCGCCCCTTGACTATGGGTCTGAATGTTTAGATTTTGGTCGTAAAACCTTTCGAACGAACGCAGTACTACATTTGGTTTGGCCTGCGTCAAAAGCTACACCTAAGGCGCCAAGCAAATTAGTTTCCCCAGTTGAAAACTGTATGAATAGTCAAAGGACCTACGACGTGATGCGTTCGTCAAGTATTGTAGGTGCACTGGACCTTGAGTCCTTGAGTCCTCCAGTCCGGCAGGACGCACTCTTTCAAGTTTGGATCTCCATCAGTAGCTAATACATCAAGGGTGTACGTTCCTAAAAAGGCTGGATCATCCGGGGGTATAGGAGTTATAGGAGTTATAGGAGTTATAGGAGTTATAGGAGTTATAGGAGTCCATTCGGCCCATTCGGCCCATTCGGCCCATTCGGCCCATTCGGCCCATTCGGC", 9, 25,3));
        Path filepath = Paths.get("src/main/resources/E_coli.txt");
        String eColi = Files.readString(filepath);
        System.out.println(ClumpFinding.clumpFinding(eColi, 9,500,3));
    }
}

